shift + alt + windows + j = join with previos cell\
alt + windows + j = join with next cell\
esc + y = change to code

In [8]:
import openmeteo_requests

import pandas as pd
import requests_cache
from retry_requests import retry
import time
import requests
pd.set_option('display.max_columns', None)

# Historical Weather Data
Saint Louis zipcodes, jan 1 2025 - dec 31 2025

In [ ]:
# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

In [4]:

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://historical-forecast-api.open-meteo.com/v1/forecast"
params = {
	"latitude": [38.855, 39.0469, 38.8772, 38.6283, 38.9444, 38.7095, 38.8067, 38.7961, 38.7609, 38.934, 38.9272, 38.7917, 38.6437, 38.9788, 38.8122, 38.2675, 38.509, 38.2322, 38.4296, 38.3915, 38.3655, 38.5282, 38.3421, 38.2103, 38.2606, 38.2492, 38.2783, 38.4829, 38.2804, 38.3094, 38.5845, 38.7336, 38.3453, 38.4501, 38.5012, 38.6114, 38.6272, 38.4371, 38.5971, 38.3357, 38.42, 38.357, 38.6542, 38.2232, 38.5883, 38.5937, 38.3344, 38.5941, 38.5042, 38.4948, 38.5867, 38.4904, 38.5773, 38.2307, 38.7761, 38.7148, 38.7537, 38.7655, 38.5613, 38.4685, 38.5561, 38.5406, 38.6315, 38.6265, 38.6312, 38.6091, 38.6399, 38.6446, 38.6611, 38.6445, 38.5897, 38.6142, 38.5733, 38.6538, 38.6618, 38.6953, 38.677, 38.59, 38.6278, 38.5982, 38.5804, 38.6845, 38.7088, 38.579, 38.5559, 38.6574, 38.551, 38.5431, 38.5513, 38.4846, 38.4886, 38.6578, 38.6035, 38.6683, 38.6708, 38.7272, 38.7398, 38.7074, 38.7533, 38.7703, 38.6058, 38.738, 38.6682, 38.615, 38.6238, 38.7415, 38.6981, 38.7185, 38.6261, 38.4677, 38.629, 38.6372, 38.6278, 38.6278, 38.6265, 38.6278, 38.6187, 38.629, 38.6693, 38.6278, 38.6278, 38.629, 38.629, 38.6278, 38.629, 38.6272, 38.6278, 38.6268, 38.6278, 38.6358, 38.6278, 38.6289, 38.6262, 38.7855, 38.7823, 38.7596, 38.7376, 38.5747, 38.7459, 38.6785, 38.6042, 38.812, 38.8133, 38.867, 38.996, 38.8788, 38.1655, 38.8075, 38.8025, 38.8071, 38.8182],
	"longitude": [-90.8631, -90.7438, -90.9689, -91.0562, -90.9183, -90.8806, -90.7019, -90.8055, -90.7709, -90.783, -90.3447, -90.6191, -91.1876, -90.9804, -91.1308, -90.3807, -90.5115, -90.5652, -90.5525, -90.3803, -90.363, -90.8483, -90.4089, -90.8212, -90.8032, -90.483, -90.6489, -90.7463, -90.3953, -90.753, -90.7545, -90.3778, -90.9809, -91.0091, -90.6275, -90.7349, -90.5184, -90.3669, -90.5455, -90.4039, -90.781, -90.6452, -90.5584, -90.382, -90.4971, -90.5655, -90.6938, -90.5144, -90.633, -90.4271, -90.6403, -90.8193, -90.6116, -90.7981, -90.3676, -90.4497, -90.4225, -90.4614, -90.4895, -90.8894, -91.0162, -90.4804, -90.1932, -90.1889, -90.2042, -90.2102, -90.3053, -90.2, -90.207, -90.2598, -90.3041, -90.2567, -90.2411, -90.2846, -90.2585, -90.3765, -90.2538, -90.2507, -90.3168, -90.234, -90.3357, -90.2692, -90.2887, -90.4089, -90.2819, -90.3569, -90.2783, -90.3724, -90.4089, -90.3883, -90.3474, -90.3073, -90.4337, -90.36, -90.2886, -90.3533, -90.3035, -90.2577, -90.1934, -90.182, -90.2922, -90.324, -90.4417, -90.3189, -90.3522, -90.3647, -90.464, -90.2334, -90.1934, -90.3055, -90.2058, -90.2449, -90.1996, -90.1996, -90.1889, -90.1996, -90.1987, -90.2058, -90.3998, -90.1996, -90.1996, -90.2058, -90.2058, -90.1996, -90.2058, -90.3115, -90.1996, -90.3113, -90.1996, -90.2452, -90.1996, -90.2048, -90.1975, -90.4858, -90.486, -90.5207, -90.6227, -90.8794, -90.6529, -90.8085, -90.9967, -91.1437, -90.858, -90.2226, -90.7403, -91.0007, -90.7364, -90.3607, -90.3111, -90.2978, -90.2866],
	"start_date": "2025-01-01",
	"end_date": "2025-12-31",
	"daily": ["temperature_2m_max", "precipitation_sum", "precipitation_hours", "uv_index_max", "wind_speed_10m_max", "shortwave_radiation_sum"],
	"timezone": "America/Chicago",
	"wind_speed_unit": "mph",
	"temperature_unit": "fahrenheit",
}
responses = openmeteo.weather_api(url, params = params)

KeyboardInterrupt:

In [ ]:

# list to store location data
location_data = []
# Process 151 locations
for response in responses:
	print(f"\nCoordinates: {response.Latitude()}°N {response.Longitude()}°E")
	print(f"Elevation: {response.Elevation()} m asl")
	print(f"Timezone: {response.Timezone()}{response.TimezoneAbbreviation()}")
	print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")
	
	# Process daily data. The order of variables needs to be the same as requested.
	daily = response.Daily()
	daily_temperature_2m_max = daily.Variables(0).ValuesAsNumpy()
	daily_precipitation_sum = daily.Variables(1).ValuesAsNumpy()
	daily_precipitation_hours = daily.Variables(2).ValuesAsNumpy()
	daily_uv_index_max = daily.Variables(3).ValuesAsNumpy()
	daily_wind_speed_10m_max = daily.Variables(4).ValuesAsNumpy()
	daily_shortwave_radiation_sum = daily.Variables(5).ValuesAsNumpy()
	
	daily_data = {"date": pd.date_range(
		start = pd.to_datetime(daily.Time() + response.UtcOffsetSeconds(), unit = "s", utc = True),
		end =  pd.to_datetime(daily.TimeEnd() + response.UtcOffsetSeconds(), unit = "s", utc = True),
		freq = pd.Timedelta(seconds = daily.Interval()),
		inclusive = "left"
	)}
	daily_data["temperature_2m_max"] = daily_temperature_2m_max
	daily_data["precipitation_sum"] = daily_precipitation_sum
	daily_data["precipitation_hours"] = daily_precipitation_hours
	daily_data["uv_index_max"] = daily_uv_index_max
	daily_data["wind_speed_10m_max"] = daily_wind_speed_10m_max
	daily_data["shortwave_radiation_sum"] = daily_shortwave_radiation_sum
	
	daily_dataframe = pd.DataFrame(data = daily_data)
	daily_dataframe["latitude"] = response.Latitude()
	daily_dataframe["longitude"] = response.Longitude()
	location_data.append(daily_dataframe)

Coordinates: 38.849788665771484°N -90.849853515625°E
Elevation: 165.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 39.05913543701172°N -90.72582244873047°E
Elevation: 134.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.88440704345703°N -90.98561096191406°E
Elevation: 175.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.61719512939453°N -91.04447174072266°E
Elevation: 175.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.934391021728516°N -90.91151428222656°E
Elevation: 160.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.71718978881836°N -90.89680480957031°E
Elevation: 236.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.81501007080078°N -90.7142105102539°E
Elevation: 177.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.79401397705078°N -90.82032012939453°E
Elevation: 181.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.76316833496094°N -90.75381469726562°E
Elevation: 186.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.92657470703125°N -90.7731704711914°E
Elevation: 157.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.929115295410156°N -90.3555908203125°E
Elevation: 134.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.782100677490234°N -90.61321258544922°E
Elevation: 152.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.65159225463867°N -91.17989349365234°E
Elevation: 155.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.992034912109375°N -90.97579193115234°E
Elevation: 167.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.811214447021484°N -91.131103515625°E
Elevation: 258.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.25457763671875°N -90.387939453125°E
Elevation: 137.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.504947662353516°N -90.50147247314453°E
Elevation: 197.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.23798370361328°N -90.56182098388672°E
Elevation: 242.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.42627716064453°N -90.54365539550781°E
Elevation: 187.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.38908004760742°N -90.37464904785156°E
Elevation: 143.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.3621826171875°N -90.37731170654297°E
Elevation: 127.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.524932861328125°N -90.84532165527344°E
Elevation: 151.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.33736038208008°N -90.41426086425781°E
Elevation: 167.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.19813537597656°N -90.80660247802734°E
Elevation: 259.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.251956939697266°N -90.8016128540039°E
Elevation: 223.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.260780334472656°N -90.49071502685547°E
Elevation: 207.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.270931243896484°N -90.66201782226562°E
Elevation: 156.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.49213409423828°N -90.74467468261719°E
Elevation: 154.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.281490325927734°N -90.38528442382812°E
Elevation: 147.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.30379867553711°N -90.7623291015625°E
Elevation: 276.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.574832916259766°N -90.7715072631836°E
Elevation: 190.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.7408332824707°N -90.3743667602539°E
Elevation: 170.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.34237289428711°N -90.96564483642578°E
Elevation: 235.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.45381546020508°N -91.02459716796875°E
Elevation: 167.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.5130729675293°N -90.63898468017578°E
Elevation: 138.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.59976577758789°N -90.73455047607422°E
Elevation: 246.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.61459732055664°N -90.52539825439453°E
Elevation: 185.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.442874908447266°N -90.36932373046875°E
Elevation: 147.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.58973693847656°N -90.56243896484375°E
Elevation: 196.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.33736038208008°N -90.41426086425781°E
Elevation: 170.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.413394927978516°N -90.78659057617188°E
Elevation: 168.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.35163497924805°N -90.65436553955078°E
Elevation: 157.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.643531799316406°N -90.55723571777344°E
Elevation: 199.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.22769546508789°N -90.39057922363281°E
Elevation: 135.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.58565139770508°N -90.49360656738281°E
Elevation: 165.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.58973693847656°N -90.56243896484375°E
Elevation: 200.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.32673645019531°N -90.69122314453125°E
Elevation: 194.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.587703704833984°N -90.52802276611328°E
Elevation: 167.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.5130729675293°N -90.63898468017578°E
Elevation: 148.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.500823974609375°N -90.43273162841797°E
Elevation: 141.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.593780517578125°N -90.63128662109375°E
Elevation: 236.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.4960823059082°N -90.81343078613281°E
Elevation: 194.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.56486129760742°N -90.59944152832031°E
Elevation: 214.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.22504425048828°N -90.80410766601562°E
Elevation: 215.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.76773452758789°N -90.37168884277344°E
Elevation: 178.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.71809005737305°N -90.44599151611328°E
Elevation: 157.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.74291229248047°N -90.40885162353516°E
Elevation: 152.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.773948669433594°N -90.47518157958984°E
Elevation: 136.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.558753967285156°N -90.49623107910156°E
Elevation: 166.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.47306442260742°N -90.88467407226562°E
Elevation: 200.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.561458587646484°N -91.014892578125°E
Elevation: 182.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.5297966003418°N -90.46446228027344°E
Elevation: 153.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62057113647461°N -90.17848205566406°E
Elevation: 149.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62057113647461°N -90.17848205566406°E
Elevation: 145.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 147.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 154.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.629066467285156°N -90.31617736816406°E
Elevation: 169.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.64960861206055°N -90.21016693115234°E
Elevation: 147.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.64960861206055°N -90.21016693115234°E
Elevation: 147.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.651729583740234°N -90.2446060180664°E
Elevation: 157.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.602169036865234°N -90.3188705444336°E
Elevation: 151.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62484359741211°N -90.24732971191406°E
Elevation: 154.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.571048736572266°N -90.25275421142578°E
Elevation: 156.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.653846740722656°N -90.27904510498047°E
Elevation: 151.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.651729583740234°N -90.2446060180664°E
Elevation: 162.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.687042236328125°N -90.37969970703125°E
Elevation: 200.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.678627014160156°N -90.24188995361328°E
Elevation: 157.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.59793472290039°N -90.25004577636719°E
Elevation: 165.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.629066467285156°N -90.31617736816406°E
Elevation: 170.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.59793472290039°N -90.25004577636719°E
Elevation: 174.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.57527160644531°N -90.32156372070312°E
Elevation: 167.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.68074417114258°N -90.27632904052734°E
Elevation: 162.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.707637786865234°N -90.27362060546875°E
Elevation: 199.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.58152770996094°N -90.4247817993164°E
Elevation: 203.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.546268463134766°N -90.28985595703125°E
Elevation: 130.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.65806579589844°N -90.3479232788086°E
Elevation: 171.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.546268463134766°N -90.28985595703125°E
Elevation: 133.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.550479888916016°N -90.358642578125°E
Elevation: 182.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.552555084228516°N -90.39303588867188°E
Elevation: 203.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.47186279296875°N -90.40101623535156°E
Elevation: 166.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.49457931518555°N -90.3296127319336°E
Elevation: 165.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.65596389770508°N -90.31349182128906°E
Elevation: 159.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.60842514038086°N -90.42213439941406°E
Elevation: 190.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.65806579589844°N -90.3479232788086°E
Elevation: 186.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.68074417114258°N -90.27632904052734°E
Elevation: 160.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.73874282836914°N -90.33987426757812°E
Elevation: 185.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.73664093017578°N -90.30538940429688°E
Elevation: 158.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.707637786865234°N -90.27362060546875°E
Elevation: 174.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.75717544555664°N -90.19922637939453°E
Elevation: 164.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.7840690612793°N -90.19647216796875°E
Elevation: 155.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.60006332397461°N -90.28445434570312°E
Elevation: 162.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.73874282836914°N -90.33987426757812°E
Elevation: 182.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.6642951965332°N -90.4512710571289°E
Elevation: 200.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.602169036865234°N -90.3188705444336°E
Elevation: 169.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.63115692138672°N -90.35061645507812°E
Elevation: 163.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.7408332824707°N -90.3743667602539°E
Elevation: 175.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.691192626953125°N -90.4486312866211°E
Elevation: 165.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.70552062988281°N -90.23916625976562°E
Elevation: 152.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62057113647461°N -90.17848205566406°E
Elevation: 141.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.465576171875°N -90.29794311523438°E
Elevation: 183.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 148.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62484359741211°N -90.24732971191406°E
Elevation: 145.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 143.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 143.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62057113647461°N -90.17848205566406°E
Elevation: 145.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 143.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 145.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 148.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.6622200012207°N -90.41682434082031°E
Elevation: 216.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 143.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 143.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 148.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 148.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 143.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 148.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.629066467285156°N -90.31617736816406°E
Elevation: 179.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 143.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.629066467285156°N -90.31617736816406°E
Elevation: 179.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 143.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62484359741211°N -90.24732971191406°E
Elevation: 145.0 m asl
Timezone: b'America/Chicago'b'GMT-5'
Timezone difference to GMT+0: -18000s

Coordinates: 38.62271499633789°N -90.21289825439453°E
Elevation: 143.0 m asl

In [ ]:
historical_weather_df = pd.concat(location_data, ignore_index=True)

In [ ]:
historical_weather_df = historical_weather_df.sort_values(["latitude","longitude","date"]).reset_index(drop=True)

In [ ]:
print(len(historical_weather_df))

55115

In [ ]:
historical_weather_df.head(10)

,date,temperature_2m_max,precipitation_sum,precipitation_hours,uv_index_max,wind_speed_10m_max,shortwave_radiation_sum,latitude,longitude
0,2025-01-01 00:00:00+00:00,40.345699,0.000000,0.0,2.75,12.521206,9.10,38.16729,-90.740654
1,2025-01-02 00:00:00+00:00,45.925697,0.100000,1.0,2.30,8.191819,7.42,38.16729,-90.740654
2,2025-01-03 00:00:00+00:00,39.355701,0.000000,0.0,2.85,11.184999,10.11,38.16729,-90.740654
3,2025-01-04 00:00:00+00:00,32.695702,1.300000,3.0,2.20,7.161894,5.43,38.16729,-90.740654
4,2025-01-05 00:00:00+00:00,28.555700,42.799995,21.0,0.45,11.124436,0.58,38.16729,-90.740654
5,2025-01-06 00:00:00+00:00,23.875700,3.700000,6.0,2.60,13.607141,8.14,38.16729,-90.740654
6,2025-01-07 00:00:00+00:00,26.395699,0.000000,0.0,2.85,8.213173,8.87,38.16729,-90.740654
7,2025-01-08 00:00:00+00:00,27.025700,0.000000,0.0,3.00,8.204027,9.97,38.16729,-90.740654
8,2025-01-09 00:00:00+00:00,32.695702,0.000000,0.0,3.00,7.519781,8.32,38.16729,-90.740654
9,2025-01-10 00:00:00+00:00,33.865700,7.900000,13.0,1.85,7.855024,3.37,38.16729,-90.740654

# Gathering paramaters for historical daily air quality data 
base URL https://aqs.epa.gov/data/api/dailyDate/byCounty?
## Paramaters
email, key, param, bdate, edate, state, county
\
param: 42101,42401,42602,44201,81102,88101\
bdate, edate : 20250101 20251231\
state: 29\
county: Saint Louis County: 189, Saint Louis City: 510
### Locations
Paramaters for Missouri, saint louis county\
State: 29\
County: 189
### pollutants
* only ones recorded: 42602, 88101 
param: 42101,42401,42602,44201,81102,88101\
pollutant: Carbon Monoxide, Sulur Dioxide, NO2, Ozone, PM10, PM2.5\
\
**Note** Excluded: Lead, Lead PM10, both for simplicity, and because they do not contribute to the AQI score.

## Locations

In [109]:
url_return_mo_counties="https://aqs.epa.gov/data/api/list/countiesByState?email=test@aqs.api&key=test&state=29"
response_mo_counties_list = requests.get(url_return_mo_counties)

In [110]:
mo_counties=response_mo_counties_list.json()

In [111]:
print(mo_counties)

{'Header': [{'status': 'Success', 'request_time': '2026-04-17T19:57:18-04:00', 'url': 'https://aqs.epa.gov/data/api/list/countiesByState?email=test@aqs.api&key=test&state=29', 'rows': 115}], 'Data': [{'code': '001', 'value_represented': 'Adair'}, {'code': '003', 'value_represented': 'Andrew'}, {'code': '005', 'value_represented': 'Atchison'}, {'code': '007', 'value_represented': 'Audrain'}, {'code': '009', 'value_represented': 'Barry'}, {'code': '011', 'value_represented': 'Barton'}, {'code': '013', 'value_represented': 'Bates'}, {'code': '015', 'value_represented': 'Benton'}, {'code': '017', 'value_represented': 'Bollinger'}, {'code': '019', 'value_represented': 'Boone'}, {'code': '021', 'value_represented': 'Buchanan'}, {'code': '023', 'value_represented': 'Butler'}, {'code': '025', 'value_represented': 'Caldwell'}, {'code': '027', 'value_represented': 'Callaway'}, {'code': '029', 'value_represented': 'Camden'}, {'code': '031', 'value_represented': 'Cape Girardeau'}, {'code': '033', 'value_represented': 'Carroll'}, {'code': '035', 'value_represented': 'Carter'}, {'code': '037', 'value_represented': 'Cass'}, {'code': '039', 'value_represented': 'Cedar'}, {'code': '041', 'value_represented': 'Chariton'}, {'code': '043', 'value_represented': 'Christian'}, {'code': '045', 'value_represented': 'Clark'}, {'code': '047', 'value_represented': 'Clay'}, {'code': '049', 'value_represented': 'Clinton'}, {'code': '051', 'value_represented': 'Cole'}, {'code': '053', 'value_represented': 'Cooper'}, {'code': '055', 'value_represented': 'Crawford'}, {'code': '057', 'value_represented': 'Dade'}, {'code': '059', 'value_represented': 'Dallas'}, {'code': '061', 'value_represented': 'Daviess'}, {'code': '063', 'value_represented': 'DeKalb'}, {'code': '065', 'value_represented': 'Dent'}, {'code': '067', 'value_represented': 'Douglas'}, {'code': '069', 'value_represented': 'Dunklin'}, {'code': '071', 'value_represented': 'Franklin'}, {'code': '073', 'value_represented': 'Gasconade'}, {'code': '075', 'value_represented': 'Gentry'}, {'code': '077', 'value_represented': 'Greene'}, {'code': '079', 'value_represented': 'Grundy'}, {'code': '081', 'value_represented': 'Harrison'}, {'code': '083', 'value_represented': 'Henry'}, {'code': '085', 'value_represented': 'Hickory'}, {'code': '087', 'value_represented': 'Holt'}, {'code': '089', 'value_represented': 'Howard'}, {'code': '091', 'value_represented': 'Howell'}, {'code': '093', 'value_represented': 'Iron'}, {'code': '095', 'value_represented': 'Jackson'}, {'code': '097', 'value_represented': 'Jasper'}, {'code': '099', 'value_represented': 'Jefferson'}, {'code': '101', 'value_represented': 'Johnson'}, {'code': '103', 'value_represented': 'Knox'}, {'code': '105', 'value_represented': 'Laclede'}, {'code': '107', 'value_represented': 'Lafayette'}, {'code': '109', 'value_represented': 'Lawrence'}, {'code': '111', 'value_represented': 'Lewis'}, {'code': '113', 'value_represented': 'Lincoln'}, {'code': '115', 'value_represented': 'Linn'}, {'code': '117', 'value_represented': 'Livingston'}, {'code': '119', 'value_represented': 'McDonald'}, {'code': '121', 'value_represented': 'Macon'}, {'code': '123', 'value_represented': 'Madison'}, {'code': '125', 'value_represented': 'Maries'}, {'code': '127', 'value_represented': 'Marion'}, {'code': '129', 'value_represented': 'Mercer'}, {'code': '131', 'value_represented': 'Miller'}, {'code': '133', 'value_represented': 'Mississippi'}, {'code': '135', 'value_represented': 'Moniteau'}, {'code': '137', 'value_represented': 'Monroe'}, {'code': '139', 'value_represented': 'Montgomery'}, {'code': '141', 'value_represented': 'Morgan'}, {'code': '143', 'value_represented': 'New Madrid'}, {'code': '145', 'value_represented': 'Newton'}, {'code': '147', 'value_represented': 'Nodaway'}, {'code': '149', 'value_represented': 'Oregon'}, {'code': '151', 'value_represented': 'Osage'}, {'code': '153', 'value_represented': 'Ozark'}, {'code': '155', 'value_represented': 'Pemiscot'}, {'code': '157', 'value_represented': 'Perry'}, {'code': '159', 'value_represented': 'Pettis'}, {'code': '161', 'value_represented': 'Phelps'}, {'code': '163', 'value_represented': 'Pike'}, {'code': '165', 'value_represented': 'Platte'}, {'code': '167', 'value_represented': 'Polk'}, {'code': '169', 'value_represented': 'Pulaski'}, {'code': '171', 'value_represented': 'Putnam'}, {'code': '173', 'value_represented': 'Ralls'}, {'code': '175', 'value_represented': 'Randolph'}, {'code': '177', 'value_represented': 'Ray'}, {'code': '179', 'value_represented': 'Reynolds'}, {'code': '181', 'value_represented': 'Ripley'}, {'code': '183', 'value_represented': 'Saint Charles'}, {'code': '185', 'value_represented': 'Saint Clair'}, {'code': '186', 'value_represented': 'Sainte Genevieve'}, {'code': '187', 'value_represented': 'Saint Francois'}, {'code': '189', 'value_represented': 'Saint Louis'}, {'code': '195', 'value_represented': 'Saline'}, {'code': '197', 'value_represented': 'Schuyler'}, {'code': '199', 'value_represented': 'Scotland'}, {'code': '201', 'value_represented': 'Scott'}, {'code': '203', 'value_represented': 'Shannon'}, {'code': '205', 'value_represented': 'Shelby'}, {'code': '207', 'value_represented': 'Stoddard'}, {'code': '209', 'value_represented': 'Stone'}, {'code': '211', 'value_represented': 'Sullivan'}, {'code': '213', 'value_represented': 'Taney'}, {'code': '215', 'value_represented': 'Texas'}, {'code': '217', 'value_represented': 'Vernon'}, {'code': '219', 'value_represented': 'Warren'}, {'code': '221', 'value_represented': 'Washington'}, {'code': '223', 'value_represented': 'Wayne'}, {'code': '225', 'value_represented': 'Webster'}, {'code': '227', 'value_represented': 'Worth'}, {'code': '229', 'value_represented': 'Wright'}, {'code': '510', 'value_represented': 'St. Louis City'}]}

In [114]:
for row in mo_counties['Data']:
    code = row['code']
    county = row['value_represented']
    if 'Louis' in county:
        print(code)

189
510

## Air quality paramaters 
code CRITERIA
value_represented Criteria Pollutants

In [2]:
url_returns_param_classes="https://aqs.epa.gov/data/api/list/classes?email=test@aqs.api&key=test"
response_param_classes = requests.get(url_returns_param_classes)
print(response_param_classes.status_code)

200

In [3]:
param_classes=response_param_classes.json()
print(param_classes['Header'])

for key,value in param_classes['Data'][0].items():
    print(key)

for row in param_classes['Data']:
    for key, value in row.items():
        print(key, value)

[{'status': 'Success', 'request_time': '2026-04-16T20:28:13-04:00', 'url': 'https://aqs.epa.gov/data/api/list/classes?email=test@aqs.api&key=test', 'rows': 27}]
code
value_represented
code AIRNOW MAPS
value_represented The parameters represented on AirNow maps (88101, 88502, and 44201)
code ALL
value_represented Select all Parameters Available
code AQI POLLUTANTS
value_represented Pollutants that have an AQI Defined
code CORE_HAPS
value_represented Urban Air Toxic Pollutants
code CRITERIA
value_represented Criteria Pollutants
code CSN DART
value_represented List of CSN speciation parameters to populate the STI DART tool
code FORECAST
value_represented Parameters routinely extracted by AirNow (STI)
code HAPS
value_represented Hazardous Air Pollutants
code IMPROVE CARBON
value_represented IMPROVE Carbon Parameters
code IMPROVE_SPECIATION
value_represented PM2.5 Speciated Parameters Measured at IMPROVE sites
code MET
value_represented Meteorological Parameters
code NATTS CORE HAPS
value_represented The core list of toxics of interest to the NATTS program.
code NATTS REQUIRED
value_represented Required compounds to be collected in the National Air Toxics Network
code PAMS
value_represented Photochemical Assessment Monitoring System
code PAMS_VOC
value_represented Volatile Organic Compound subset of the PAMS Parameters
code PM COARSE
value_represented PM between 2.5 and 10 micrometers
code PM10 SPECIATION
value_represented PM10 Speciated Parameters
code PM2.5 CONT NONREF
value_represented PM2.5 Continuous, Nonreference Methods
code PM2.5 MASS/QA
value_represented PM2.5 Mass and QA Parameters
code SCHOOL AIR TOXICS
value_represented School Air Toxics Program Parameters
code SPECIATION
value_represented PM2.5 Speciated Parameters
code SPECIATION CARBON
value_represented PM2.5 Speciation Carbon Parameters
code SPECIATION CATION/ANION
value_represented PM2.5 Speciation Cation/Anion Parameters
code SPECIATION METALS
value_represented PM2.5 Speciation Metal Parameters
code UATMP CARBONYL
value_represented Urban Air Toxics Monitoring Program Carbonyls
code UATMP VOC
value_represented Urban Air Toxics Monitoring Program VOCs
code VOC
value_represented Volatile organic compounds

In [6]:
url_criteria_pollutants="https://aqs.epa.gov/data/api/list/parametersByClass?email=test@aqs.api&key=test&pc=CRITERIA"
response_criteria_pollutants=requests.get(url_criteria_pollutants)
print(response_criteria_pollutants.status_code)

200

In [ ]:
criteria_pollutants=response_criteria_pollutants.json()
for row in criteria_pollutants['Data']:
    for key, value in row.items():
        print(key, value)

code 14129
value_represented Lead (TSP) LC
code 42101
value_represented Carbon monoxide
code 42401
value_represented Sulfur dioxide
code 42602
value_represented Nitrogen dioxide (NO2)
code 44201
value_represented Ozone
code 81102
value_represented PM10 Total 0-10um STP
code 85129
value_represented Lead PM10 LC FRM/FEM
code 88101
value_represented PM2.5 - Local Conditions

## Historical Air Data Extraction

In [ ]:
KEY_AQS="mauvefox81"
EMAIL="ltfy4d@umsystem.edu"
def get_air_response(param_codes,county_code,key,email):
    """returns a response in json format for given parameters *up to five
    and given county code"""
    url_hist_air_quality="https://aqs.epa.gov/data/api/sampleData/byCounty?"
    KEY=key
    EMAIL=email

    params={
        'email': EMAIL,
        'key' : KEY,
        'param': param_codes,
        'bdate' : '20250101',
        'edate' : '20251231',
        'state' : '29',
        'county' : county_code
    }

    response=requests.get(url_hist_air_quality,params=params)
    if response.status_code==200:
        print("Success")
        return response.json()
    else:
        print(response.text)

In [ ]:
# codes 189 county, 510 city
def get_air_data(code):
    # lists of parameter codes
    # carbon monoxide, sulfur dioxide, nitrogen dioxide
    CO_SO2_NO2=['42101','42401','42602']
    Ozone_PM10_PM25=['44201','81102','88101']

    # responses for given county code, for params
    response_CO_SO2_NO2=get_air_response(CO_SO2_NO2,code)
    time.sleep(10)
    response_Ozone_PM10_PM25 = get_air_response(Ozone_PM10_PM25,code)

    # convert the json into pandas dataframes
    df_CO_SO2_NO2 = pd.json_normalize(response_CO_SO2_NO2, record_path=['Data'])
    df_Ozone_PM10_PM25=pd.json_normalize(response_Ozone_PM10_PM25, record_path=['Data'])
    # concatinate the dataframes 
    # for each set of pollutants into one dataframe
    air_quality=pd.concat([df_Ozone_PM10_PM25,df_CO_SO2_NO2], ignore_index=True)

    return air_quality

In [35]:
# data dictionary
class DataDict:

    def __init__(self,df):
        """Collects all methods for creating a data dictionary"""
        self.df=df
        self.data_dict= pd.DataFrame({
        "column": self.df.columns,
        "dtype" : self.df.dtypes.astype(str).values,
        "missingness" : self.df.isna().mean()*100,
        "description": "",
        "notes" : ""
        })

    def get_data_dict(self):
        return self.data_dict
        
    def _check_initialized(self):
        if self.data_dict is None:
            raise ValueError("Data dictionary not created yet. Run set_data_dict() first.")
            

    def update_description(self,column,description):
        """Updates the description column"""
        self._check_initialized()

        mask=self.data_dict["column"]==column

        if not mask.any():
            print("column not found")
            return
        self.data_dict.loc[mask,"description"]=description
        print(self.data_dict.loc[mask])
        
    def update_notes(self,column,note):
        """Updates the notes section"""
        self._check_initialized()

        mask=self.data_dict["column"]==column
        if not mask.any():
            print("column not found")
            return
        self.data_dict.loc[mask,"notes"]=note
        print(self.data_dict.loc[mask])
    def remove_column(self, column):
        """Removes a column row from the data dictionary only"""
        self._check_initialized()

        self.data_dict = self.data_dict[self.data_dict["column"] != column]

In [ ]:
def data_dict_builder(dataframe):
    """populates the data dictionaries"""
    data_dict=DataDict(dataframe)
    
    data_dict.update_description('state_code','FIPS code for state')
    data_dict.update_description('county_code','FIPS code for county')
    data_dict.update_description('site_number', 'Monitoring Station ID')
    data_dict.update_description('parameter_code','AQS pollutant code') 
    data_dict.update_description('poc','parameter occorence code')
    data_dict.update_description('latitude','geographic area')
    data_dict.update_description('longitude','geographic area')
    data_dict.update_description('datum','geodectic reference system for lat log')
    data_dict.update_description('parameter','pollutant name')
    data_dict.update_description('sample_duration','1hr,8hr,24hr period')
    data_dict.update_description('sample_duration_code','1:1hr,5:8hr,7:24hr')
    data_dict.update_description('sample_duration_type','HOURLY:1hr avg, DAILY:24hr avg, 8hr RUN AVG:8hr rolling avg')
    data_dict.update_description('pollutant_standard','EPA regulatory framework defining acceptable threshold')
    data_dict.update_description('date_local','date collected')
    data_dict.update_description('units_of_measure','units to measure concentration')
    data_dict.update_description('event_type','flagging whether data point effected by exceptional environmental event')
    data_dict.update_description('observation_count','# of observations used to calculate reported summary value')
    data_dict.update_description('observation_percent','how complete the data is for that time period')
    data_dict.update_notes('observation_percent','filter out below 75%')
    data_dict.update_description('validity_indicator','passed AQ checks')
    data_dict.update_description('arithmetic_mean','concentration over 24 hr period')
    data_dict.update_description('first_max_value','peak exposure concentration')
    data_dict.update_notes('first_max_value','best choice for aqi prediction')
    data_dict.update_description('first_max_hour','when peak exposure occored')
    data_dict.update_description('time_local','Time sample was recorded')
    data_dict.update_description('sample_measurement','concentration recorded')
    data_dict.update_description('units_of_measure','units of measure')
    data_dict.update_description('units_of_measure_code','code corresponding to units of measure')
    data_dict.update_description('sample_frequency','how often measured')
    data_dict.update_notes('sample_frequency','HOURLY, every 6th day')
    data_dict.update_description('detection_limit','concentration detected at')
    data_dict.update_description('qualifier','code for context info')
    data_dict.update_notes('qualifier','some will need replacement with mean')
    data_dict.update_description('method_type','FEM:automated,FRM:laboratory')
    data_dict.update_description('method','detailed info on method')
    data_dict.update_description('method_code','method code')
    data_dict.update_description('state','state')
    data_dict.update_description('county','county')
    data_dict.update_description('date_of_last_change','date added to database')
    data_dict.update_description('cbsa_code','Core base statistical area code')
    data_dict.update_description('uncertainty','Confidence Level')
    data_dict.update_notes('poc','code for measurements at same site, location and time')
    return data_dict

In [ ]:
county_dict_builder=populate_data_dict(county_air_quality)
city_dict_builder=populate_data_dict(city_air_quality)

                column dtype  missingness          description notes
state_code  state_code   str          0.0  FIPS code for state
                  column dtype  missingness           description notes
county_code  county_code   str          0.0  FIPS code for county
                  column dtype  missingness            description notes
site_number  site_number   str          0.0  Monitoring Station ID
                        column dtype  missingness         description notes
parameter_code  parameter_code   str          0.0  AQS pollutant code
    column  dtype  missingness               description notes
poc    poc  int64          0.0  parameter occorence code
            column    dtype  missingness      description notes
latitude  latitude  float64          0.0  geographic area
              column    dtype  missingness      description notes
longitude  longitude  float64          0.0  geographic area
      column dtype  missingness                             description notes
datum  datum   str          0.0  geodectic reference system for lat log
              column dtype  missingness     description notes
parameter  parameter   str          0.0  pollutant name
                          column dtype  missingness          description notes
sample_duration  sample_duration   str          0.0  1hr,8hr,24hr period
                                    column dtype  missingness  \
sample_duration_code  sample_duration_code   str          0.0

                             description notes
sample_duration_code  1:1hr,5:8hr,7:24hr
column not found
column not found
                column dtype  missingness     description notes
date_local  date_local   str          0.0  date collected
                            column dtype  missingness  \
units_of_measure  units_of_measure   str          0.0

                                     description notes
units_of_measure  units to measure concentration
column not found
column not found
column not found
column not found
column not found
column not found
column not found
column not found
column not found
                column dtype  missingness               description notes
time_local  time_local   str          0.0  Time sample was recorded
                                column    dtype  missingness  \
sample_measurement  sample_measurement  float64     3.877492

                               description notes
sample_measurement  concentration recorded
                            column dtype  missingness       description notes
units_of_measure  units_of_measure   str          0.0  units of measure
                                      column dtype  missingness  \
units_of_measure_code  units_of_measure_code   str          0.0

                                                  description notes
units_of_measure_code  code corresponding to units of measure
                            column dtype  missingness         description  \
sample_frequency  sample_frequency   str          0.0  how often measured

                 notes
sample_frequency
                            column dtype  missingness         description  \
sample_frequency  sample_frequency   str          0.0  how often measured

                                  notes
sample_frequency  HOURLY, every 6th day
                          column    dtype  missingness  \
detection_limit  detection_limit  float64          0.0

                               description notes
detection_limit  concentration detected at
              column dtype  missingness            description notes
qualifier  qualifier   str    96.122508  code for context info
              column dtype  missingness            description  \
qualifier  qualifier   str    96.122508  code for context info

                                          notes
qualifier  some will need replacement with mean
                  column dtype  missingness                   description  \
method_type  method_type   str          0.0  FEM:automated,FRM:laboratory

            notes
method_type
        column dtype  missingness              description notes
method  method   str          0.0  detailed info on method
                  column dtype  missingness  description notes
method_code  method_code   str          0.0  method code
      column dtype  missingness description notes
state  state   str          0.0       state
        column dtype  missingness description notes
county  county   str          0.0      county
                                  column dtype  missingness  \
date_of_last_change  date_of_last_change   str          0.0

                                description notes
date_of_last_change  date added to database
              column dtype  missingness                      description notes
cbsa_code  cbsa_code   str          0.0  Core base statistical area code
                  column   dtype  missingness       description notes
uncertainty  uncertainty  object        100.0  Confidence Level
    column  dtype  missingness               description  \
poc    poc  int64          0.0  parameter occorence code

                                                 notes
poc  code for measurements at same site, location a...
                column dtype  missingness          description notes
state_code  state_code   str          0.0  FIPS code for state
                  column dtype  missingness           description notes
county_code  county_code   str          0.0  FIPS code for county
                  column dtype  missingness            description notes
site_number  site_number   str          0.0  Monitoring Station ID
                        column dtype  missingness         description notes
parameter_code  parameter_code   str          0.0  AQS pollutant code
    column  dtype  missingness               description notes
poc    poc  int64          0.0  parameter occorence code
            column    dtype  missingness      description notes
latitude  latitude  float64          0.0  geographic area
              column    dtype  missingness      description notes
longitude  longitude  float64          0.0  geographic area
      column dtype  missingness                             description notes
datum  datum   str          0.0  geodectic reference system for lat log
              column dtype  missingness     description notes
parameter  parameter   str          0.0  pollutant name
                          column dtype  missingness          description notes
sample_duration  sample_duration   str          0.0  1hr,8hr,24hr period
                                    column dtype  missingness  \
sample_duration_code  sample_duration_code   str          0.0

                             description notes
sample_duration_code  1:1hr,5:8hr,7:24hr
column not found
column not found
                column dtype  missingness     description notes
date_local  date_local   str          0.0  date collected
                            column dtype  missingness  \
units_of_measure  units_of_measure   str          0.0

                                     description notes
units_of_measure  units to measure concentration
column not found
column not found
column not found
column not found
column not found
column not found
column not found
column not found
column not found
                column dtype  missingness               description notes
time_local  time_local   str          0.0  Time sample was recorded
                                column    dtype  missingness  \
sample_measurement  sample_measurement  float64     4.372127

                               description notes
sample_measurement  concentration recorded
                            column dtype  missingness       description notes
units_of_measure  units_of_measure   str          0.0  units of measure
                                      column dtype  missingness  \
units_of_measure_code  units_of_measure_code   str          0.0

                                                  description notes
units_of_measure_code  code corresponding to units of measure
                            column dtype  missingness         description  \
sample_frequency  sample_frequency   str          0.0  how often measured

                 notes
sample_frequency
                            column dtype  missingness         description  \
sample_frequency  sample_frequency   str          0.0  how often measured

                                  notes
sample_frequency  HOURLY, every 6th day
                          column    dtype  missingness  \
detection_limit  detection_limit  float64          0.0

                               description notes
detection_limit  concentration detected at
              column dtype  missingness            description notes
qualifier  qualifier   str    95.627873  code for context info
              column dtype  missingness            description  \
qualifier  qualifier   str    95.627873  code for context info

                                          notes
qualifier  some will need replacement with mean
                  column dtype  missingness                   description  \
method_type  method_type   str          0.0  FEM:automated,FRM:laboratory

            notes
method_type
        column dtype  missingness              description notes
method  method   str          0.0  detailed info on method
                  column dtype  missingness  description notes
method_code  method_code   str          0.0  method code
      column dtype  missingness description notes
state  state   str          0.0       state
        column dtype  missingness description notes
county  county   str          0.0      county
                                  column dtype  missingness  \
date_of_last_change  date_of_last_change   str          0.0

                                description notes
date_of_last_change  date added to database
              column dtype  missingness                      description notes
cbsa_code  cbsa_code   str          0.0  Core base statistical area code
                  column   dtype  missingness       description notes
uncertainty  uncertainty  object        100.0  Confidence Level
    column  dtype  missingness               description  \
poc    poc  int64          0.0  parameter occorence code

                                                 notes
poc  code for measurements at same site, location a...

In [ ]:
county_dict=county_dict_builder.get_data_dict()

In [ ]:
county_dict

,column,dtype,missingness,description,notes
state_code,state_code,str,0.000000,FIPS code for state,
county_code,county_code,str,0.000000,FIPS code for county,
site_number,site_number,str,0.000000,Monitoring Station ID,
parameter_code,parameter_code,str,0.000000,AQS pollutant code,
poc,poc,int64,0.000000,parameter occorence code,"code for measurements at same site, location a..."
latitude,latitude,float64,0.000000,geographic area,
longitude,longitude,float64,0.000000,geographic area,
datum,datum,str,0.000000,geodectic reference system for lat log,
parameter,parameter,str,0.000000,pollutant name,
date_local,date_local,str,0.000000,date collected,
time_local,time_local,str,0.000000,Time sample was recorded,
date_gmt,date_gmt,str,0.000000,,
time_gmt,time_gmt,str,0.000000,,
sample_measurement,sample_measurement,float64,3.877492,concentration recorded,
units_of_measure,units_of_measure,str,0.000000,units of measure,
units_of_measure_code,units_of_measure_code,str,0.000000,code corresponding to units of measure,
sample_duration,sample_duration,str,0.000000,"1hr,8hr,24hr period",
sample_duration_code,sample_duration_code,str,0.000000,"1:1hr,5:8hr,7:24hr",
sample_frequency,sample_frequency,str,0.000000,how often measured,"HOURLY, every 6th day"
detection_limit,detection_limit,float64,0.000000,concentration detected at,
uncertainty,uncertainty,object,100.000000,Confidence Level,
qualifier,qualifier,str,96.122508,code for context info,some will need replacement with mean
method_type,method_type,str,0.000000,"FEM:automated,FRM:laboratory",
method,method,str,0.000000,detailed info on method,
method_code,method_code,str,0.000000,method code,
state,state,str,0.000000,state,
county,county,str,0.000000,county,
date_of_last_change,date_of_last_change,str,0.000000,date added to database,
cbsa_code,cbsa_code,str,0.000000,Core base statistical area code,

# Filtering the data set
Based on the dictionary, we can remove a number of collumns to make the data easier to work with for our problemb

## Drop: 
### Info not recorded, duplicate information
* uncertainty- was not recorded
* state, county, date_of_last_change, cbsa_code
* datum
* date_gmt
* time_gmt
* units_of_measure_code
* sample_duration_code
### Extranious information
* method,method_type,method_code - not needed for this problem 
* detection_limit - extra detail not needed for this problem

### Potential outliars that needs inspection
* qualifier - samples with qualifier may need replacement 
* samples with missing sample_measurement need inspection
### Method to reduce samples to one record per criteria per day
* verify for below, that each sample has teh same sample_duration
* site_number, parameter, date_local, time_local, poc 
  * sample_measurement take the mean

# Removing Unneeded Columns

In [ ]:
def create_updated_df(data):
    """ returns copy of dataframe with updated columns"""
    to_drop=['uncertainty','state_code','county_code','state','county','datum','date_of_last_change','cbsa_code','date_gmt','time_gmt','units_of_measure_code','sample_duration_code','method','method_type','method_code','detection_limit']

    return data.drop(columns=to_drop)
    
def create_updated_data_dict_builder(data_dict):
    """returns copy of data dict builder object with updated columns"""
    to_drop=['uncertainty','state_code','county_code','state','county','datum','date_of_last_change','cbsa_code','date_gmt','time_gmt','units_of_measure_code','sample_duration_code','method','method_type','method_code','detection_limit']

    updated_dict_builder=data_dict_builder
    for col in to_drop:
        updated_dict_builder.remove_column(col)
    return updated_dict_builder

In [ ]:
cols=['site_number','parameter','poc','']

,column,dtype,missingness,description,notes
site_number,site_number,str,0.000000,Monitoring Station ID,
parameter_code,parameter_code,str,0.000000,AQS pollutant code,
poc,poc,int64,0.000000,parameter occorence code,"code for measurements at same site, location a..."
latitude,latitude,float64,0.000000,geographic area,
longitude,longitude,float64,0.000000,geographic area,
parameter,parameter,str,0.000000,pollutant name,
date_local,date_local,str,0.000000,date collected,
time_local,time_local,str,0.000000,Time sample was recorded,
sample_measurement,sample_measurement,float64,3.877492,concentration recorded,
units_of_measure,units_of_measure,str,0.000000,units of measure,
sample_duration,sample_duration,str,0.000000,"1hr,8hr,24hr period",
sample_frequency,sample_frequency,str,0.000000,how often measured,"HOURLY, every 6th day"
qualifier,qualifier,str,96.122508,code for context info,some will need replacement with mean

In [ ]:
# exploring columns with qualifiers
def get_qualifier_info(dataframe):
    info={}
    qualifiers=dataframe.loc[dataframe['qualifier'].notna()]
    info['num_rows']=len(qualifiers)
    info['values']=qualifiers['qualifier'].unique()
    info['df_qualifiers']=qualifiers
    return info

In [ ]:
qualifier_data=get_qualifier_info()

In [ ]:
print(f"number of rows w qualifiers: {qualifier_data['num_rows']}\nQualifier values:{qualifier_data['values']}")

number of rows w qualifiers: 671
Qualifier values:<StringArray>
[                                                   'BF - Precision/Zero/Span.',
                                                               'BL - QA Audit.',
 'DA - Aberrant Data (Corrupt Files, Aberrant Chromatography, Spikes, Shifts).',
                                                            'AT - Calibration.',
                                                          'AV - Power Failure.',
                                                    'AN - Machine Malfunction.',
                                            'BA - Maintenance/Routine Repairs.',
                                                     'AL - Voided by Operator.',
                                                'BC - Multi-point Calibration.',
                                              'EC - Exceeds Critical Criteria.',
                               'QV - Quality Control Multi-point Verification.']
Length: 11, dtype: str

## Qualifiers
MNAR -\
Qualifiers indicate the data was corrupted or not collected.
96.122508 have a code ~ 4% with a code
## Decision
These rows will be replaced with the mean value for that paramater.

## Data Validation
For Saint

In [ ]:
# sample_measurement
aq_hs_df[["parameter", "units_of_measure"]].drop_duplicates()

                     parameter             units_of_measure
0     PM2.5 - Local Conditions  Micrograms/cubic meter (LC)
8775    Nitrogen dioxide (NO2)            Parts per billion

In [ ]:
aq_hs_df['parameter'].value_counts()

parameter
PM2.5 - Local Conditions    8775
Nitrogen dioxide (NO2)      8530
Name: count, dtype: int64